const usuarios = [
  {
    id: '1',
    first_name: 'Ramon',
    second_name: 'Landino',
    last_name: 'Salazar',
    email: 'ramonsito@gmail.com',
    photo: 'https://i.pinimg.com/originals/56/c7/a4/56c7a426054460c40d1eec51e7121891.jpg',
    rol: 'Usuario',
    proveedor: null,
    compras: [],
    resenas: [],
    subscribe_blog: true,
    disabled: false,
  },
  {
    id: '2',
    first_name: 'Richard',
    second_name: null,
    last_name: 'Marlo',
    email: 'rich@gmail.com',
    photo: null,
    rol: 'Proveedor',
    proveedor: null,
    compras: [],
    resenas: [],
    subscribe_blog: false,
    disabled: false,
  },
  {
    id: '3',
    first_name: 'Maria',
    second_name: 'Escarlata',
    last_name: 'Nuñez',
    email: 'mari11@gmail.com',
    photo: 'https://i.pinimg.com/originals/56/c7/a4/56c7a426054460c40d1eec51e7121891.jpg',
    rol: 'Usuario',
    proveedor: null,
    compras: [],
    resenas: [],
    subscribe_blog: true,
    disabled: false,
  },
  {
    id: '4',
    first_name: 'Jose',
    second_name: null,
    last_name: 'Tortorio',
    email: 'jose80@gmail.com',
    photo: null,
    rol: 'Usuario',
    proveedor: null,
    compras: [],
    resenas: [],
    subscribe_blog: false,
    disabled: false,
  },
  {
    id: '5',
    first_name: 'Tobi',
    second_name: null,
    last_name: 'Akats',
    email: 'bito@gmail.com',
    photo: 'https://i.pinimg.com/originals/56/c7/a4/56c7a426054460c40d1eec51e7121891.jpg',
    rol: 'Proveedor',
    proveedor: null,
    compras: [],
    resenas: [],
    subscribe_blog: true,
    disabled: false,
  },
  {
    id: '6',
    first_name: 'Gaspar',
    second_name: 'Carlos',
    last_name: 'Valdez',
    email: 'gaspi@gmail.com',
    photo: null,
    rol: 'Usuario',
    proveedor: null,
    compras: [],
    resenas: [],
    subscribe_blog: false,
    disabled: true,
  },
];

export default usuarios;
